spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create-drop
      # ddl-auto: validate ( sql.init.mode = always )
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_calendar
    username: root
    password: root

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_calendar
    username: root
    password: root

---
spring:
  config:
    activate:
      on-profile: poor
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dev_calendar
    username: root
    password: root
